### ISSUE TITLE
Seg. fault with ROOT v6.04

### ISSUE THREAD

**Issue by robbietuk** [UCL/STIR#350]
On multiple installs of STIR using root v6.04. 

Attempting to execute lm_to_projdata (or other access root files) leads to a segmentation fault with the error message:

```
WARNING: KeyParser warning: unrecognized keyword: view offset (degrees)


WARNING: KeyParser warning: unrecognized keyword: default number of arc-corrected bins


WARNING: CListModeDataROOT: Trying to figure out the scanner geometry from the information given in the ROOT header file.

INFO: CListModeDataROOT: used ROOT file RobbiesPhantom1_muMap_merged.root

WARNING: 
Interfile warning: I did not recognise the scanner neither from 
'originating_system' or 'number of detectors per ring' and 'number of rings'.


WARNING: Scanner User_defined_scanner: axial bucket info is not set (probably irrelevant unless you use dead-time correction that needs this info)

WARNING: Interfile parsing ended up with the following scanner:
Scanner parameters:= 
Scanner type := User_defined_scanner
Number of rings                          := 24
Number of detectors per ring             := 576
Inner ring diameter (cm)                 := 81.02
Average depth of interaction (cm)        := 0.94
Distance between rings (cm)              := 0.654
Default bin size (cm)                    := 0.21306
View offset (degrees)                    := 0
Maximum number of non-arc-corrected bins := 381
Default number of arc-corrected bins     := 381
Number of blocks per bucket in transaxial direction         := 1
Number of blocks per bucket in axial direction              := 4
Number of crystals per block in axial direction             := 24
Number of crystals per block in transaxial direction        := 9
Number of detector layers                                   := 1
Number of crystals per singles unit in axial direction      := 24
Number of crystals per singles unit in transaxial direction := 9
end scanner parameters:=


LmToProjData NOT Using FRAME_BASED_DT_CORR

Processing time frame 1

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007f33eab1adbc in waitpid () from /lib64/libc.so.6
#1  0x00007f33eaa9dcc2 in do_system () from /lib64/libc.so.6
#2  0x00007f33ee1ef954 in TUnixSystem::StackTrace() () from /shared/ucl/apps/ROOT/6.04.00/gnu-4.9.2/lib/root/libCore.so
#3  0x00007f33ee1f18ec in TUnixSystem::DispatchSignals(ESignals) () from /shared/ucl/apps/ROOT/6.04.00/gnu-4.9.2/lib/root/libCore.so
#4  <signal handler called>
#5  0x000000000054f441 in stir::CListEventCylindricalScannerWithDiscreteDetectors::get_bin(stir::Bin&, stir::ProjDataInfo const&) const ()
#6  0x00000000005491ad in stir::LmToProjData::get_bin_from_event(stir::Bin&, stir::CListEvent const&) const ()
#7  0x000000000054ad1b in stir::LmToProjData::process_data() ()
#8  0x00000000004fa883 in main ()
===========================================================


The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x000000000054f441 in stir::CListEventCylindricalScannerWithDiscreteDetectors::get_bin(stir::Bin&, stir::ProjDataInfo const&) const ()
#6  0x00000000005491ad in stir::LmToProjData::get_bin_from_event(stir::Bin&, stir::CListEvent const&) const ()
#7  0x000000000054ad1b in stir::LmToProjData::process_data() ()
#8  0x00000000004fa883 in main ()
===========================================================
```
This is on a system:
```
cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.4 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
```
with gcc 4.9.2

I have successfully run lm_to_project data by compiling stir with:
    ROOT v5.34.36 on this system; and
    ROOT v6.16 on a MACos system

It appears there is an issue with STIR using ROOT v6.04. I am pretty sure I tried some other early releases of ROOT v6.##

**Comment by robbietuk** [comment]
Fixed by completely by rebuilding from scratch. I am able to unlist using ROOT 6.04.
