### ISSUE TITLE
python list mode (ROOT) 

### ISSUE THREAD

**Issue by robbietuk** [UCL/STIR#353]
I have been trying to stabilise my STIR install for use with Python and ROOT on the UCL cluster (where I dont have `/usr/bin` or `/usr/local/bin` permissions). I have been finding that accessing a ROOT file's list mode data in Python can be temperamental. 

### System configuration

```
[rmaprrt@login12 STIR_testing]$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.4 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"
```
- STIR master branch (2 commits behind UCL:master.)
- ROOT 6.04 (pre-installed on the UCL cluster)
- SWIG 3.0.12 (compiled myself from source)
- Python 3.6.3 with numpy (pre-installed on the UCL cluster)
- gcc (GCC) 4.9.2 (pre-installed on the UCL cluster)
- boost/1.63.0 (pre-installed on the UCL cluster)

### Command Line Executables
Note, all command line executions, such as `OSMAPOSL <parameter_file>`, work perfectly fine. I am also sure that the .root data file used and parameter file can be used from the command line.

### test_python_lm_recon.py
I wrote the following python script to perform OSMAPOSL reconstructions:
```
# test_python_lm_recon.py

def test_python_lm_recon():
    import stir, stirextra
    print("\n\nTESTING LISTMODE\n")

    parameter_filename = "simple_cylinder_LM_1.par"

    recon = stir.OSMAPOSLReconstruction3DFloat(parameter_filename)
    current_estimate_target = recon.get_initial_data_ptr()
    recon.get_objective_function().set_use_subset_sensitivities(False)
    recon.set_up(current_estimate_target)
    current_estimate_target.fill(1)
    
    recon.reconstruct(current_estimate_target)

    gradient_target = current_estimate_target.get_empty_copy()
    recon.get_objective_function().compute_sub_gradient(gradient_target, current_estimate_target, 1)

    print("\n\nPASSED LM RECON\n")

if __name__ == "__main__":
    import os, time
    os.chdir("source")
    test_python_lm_recon()

```

When this script is run by `python test_python_lm_recon.py` gives the follow message and segmentation violation (slightly modified to improve readability): 

```
[rmaprrt@login12 STIR_testing]$ python test_python_lm_recon.py 

TESTING LISTMODE

WARNING: KeyParser warning: unrecognized keyword: listmode scan time
WARNING: KeyParser warning: unrecognized keyword: subset sampling method

FactoryRegistry: key RelativeDifference not found in current registry
4 possible values are:
FilterRootPrior
None
PLS
Quadratic

Using value corresponding to key "None"
WARNING: KeyParser warning: unrecognized keyword: relative difference prior parameters
WARNING: KeyParser warning: unrecognized keyword: penalisation factor
WARNING: KeyParser warning: unrecognized keyword: only 2d
WARNING: KeyParser warning: unrecognized keyword: gamma value
WARNING: KeyParser warning: unrecognized keyword: end relative difference prior parameters
WARNING: KeyParser warning: unrecognized keyword: view offset (degrees)
WARNING: KeyParser warning: unrecognized keyword: default number of arc-corrected bins
WARNING: CListModeDataROOT: Trying to figure out the scanner geometry from the information given in the ROOT header file.

INFO: CListModeDataROOT: used ROOT file simple_cylinder_mu_1.root

INFO: osmaposlparameters :=
output filename prefix := my_OSEM_LM
output file format type := Interfile
interfile output file format parameters :=
byte order := LITTLEENDIAN
number format := float
number of bytes per pixel := 4
scale to write data := 0
end interfile output file format parameters := 

post-filter type := None
disable output := 0
objective function type := PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin
poissonloglikelihoodwithlinearmodelformeanandlistmodedatawithprojmatrixbybin parameters :=
prior type := None
sensitivity filename := my_sens_lm200.hv
subset sensitivity filenames := 
recompute sensitivity := 0
use subset sensitivities := 0
list mode filename := simple_cylinder_mu_1.hroot
zoom := 1
z zoom := 1
xy output image size (in pixels) := 200
z output image size (in pixels) := -1
z offset (in mm) := 0
time frame definition filename := 
time frame number := 1
bin normalisation type := None

max ring difference num to process := 23
matrix type := Ray Tracing
ray tracing matrix parameters :=
disable caching := 0
store only basic bins in cache := 1
restrict to cylindrical fov := 1
number of rays in tangential direction to trace for each bin := 1
use actual detector boundaries := 0
do symmetry 90degrees min phi := 1
do symmetry 180degrees min phi := 1
do symmetry swap segment := 1
do symmetry swap s := 1
do symmetry shift z := 1
end ray tracing matrix parameters := 

additive sinogram := 0
num events to use := 0
end poissonloglikelihoodwithlinearmodelformeanandlistmodedatawithprojmatrixbybin parameters := 

number of subiterations := 1
start at subiteration number := 1
save estimates at subiteration intervals := 1
initial estimate := 1
number of subsets := 8
start at subset := 0
uniformly randomise subset order := 0
inter-iteration filter subiteration interval := 0
inter-iteration filter type := None
report objective function values interval := 0
enforce initial positivity condition := 1
inter-update filter subiteration interval := 0
inter-update filter type := None
map model := additive
maximum relative change := 3.40282e+38
minimum relative change := 0
write update image := 0
end := 
end osmaposlparameters := 

INFO: Determined voxel size by dividing default_bin_size (2.1306) by zoom

INFO: Reading sensitivity from 'my_sens_lm200.hv'

WARNING: WARNING: ProjMatrixByBinUsingRayTracing used for pixel size (in x,y) that is smaller than the bin size divided by num_tangential_LORs.
This matrix will completely miss some voxels for some (or all) views.

WARNING: WARNING: ProjMatrixByBinUsingRayTracing used for pixel size (in x,y) that is smaller than the bin size divided by num_tangential_LORs.
This matrix will completely miss some voxels for some (or all) views.

WARNING: WARNING: ProjMatrixByBinUsingRayTracing used for pixel size (in x,y) that is smaller than the bin size divided by num_tangential_LORs.
This matrix will completely miss some voxels for some (or all) views.

INFO: Now processing subset #: 0

 *** Break *** segmentation violation

===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007f7da5747e09 in waitpid () from /lib64/libc.so.6
#1  0x00007f7da56cacc2 in do_system () from /lib64/libc.so.6
#2  0x00007f7da56cb071 in system () from /lib64/libc.so.6
#3  0x00007f7d9d108824 in TUnixSystem::StackTrace() () from /shared/ucl/apps/ROOT/5.34.36-FFTW-3.3.6-GSL-2.4/gnu-4.9.2/lib/root/libCore.so
#4  0x00007f7d9d10a91c in TUnixSystem::DispatchSignals(ESignals) () from /shared/ucl/apps/ROOT/5.34.36-FFTW-3.3.6-GSL-2.4/gnu-4.9.2/lib/root/libCore.so
#5  <signal handler called>
#6  0x00007f7d9e8fc8f1 in stir::CListEventCylindricalScannerWithDiscreteDetectors::get_bin(stir::Bin&, stir::ProjDataInfo const&) const () from /home/rmaprrt/bin/STIR_bin/install/python/_stir.so
#7  0x00007f7d9e99cc37 in stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin<stir::DiscretisedDensity<3, float> >::compute_sub_gradient_without_penalty_plus_sensitivity(stir::DiscretisedDensity<3, float>&, stir::DiscretisedDensity<3, float> const&, int) () from /home/rmaprrt/bin/STIR_bin/install/python/_stir.so
#8  0x00007f7d9e8e3ab9 in stir::OSMAPOSLReconstruction<stir::DiscretisedDensity<3, float> >::update_estimate(stir::DiscretisedDensity<3, float>&) () from /home/rmaprrt/bin/STIR_bin/install/python/_stir.so
#9  0x00007f7d9e9371b5 in stir::IterativeReconstruction<stir::DiscretisedDensity<3, float> >::reconstruct(boost::shared_ptr<stir::DiscretisedDensity<3, float> > const&) () from /home/rmaprrt/bin/STIR_bin/install/python/_stir.so
#10 0x00007f7d9e808662 in _wrap_IterativeReconstruction3DFloat_reconstruct () from /home/rmaprrt/bin/STIR_bin/install/python/_stir.so
#11 0x00007f7da643de29 in _PyCFunction_FastCallDict (func_obj=0x7f7d69d507e0, args=0xcfad38, nargs=<optimized out>, kwargs=kwargs
entry=0x0) at Objects/methodobject.c:234
#12 0x00007f7da643e0d7 in _PyCFunction_FastCallKeywords (func=func
entry=0x7f7d69d507e0, stack=stack
entry=0xcfad38, nargs=<optimized out>, kwnames=kwnames
entry=0x0) at Objects/methodobject.c:294
#13 0x00007f7da64d5e83 in call_function (pp_stack=pp_stack
entry=0x7ffc8905ae60, oparg=<optimized out>, kwnames=kwnames
entry=0x0) at Python/ceval.c:4824
#14 0x00007f7da64db3f6 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3322
#15 0x00007f7da64d5150 in _PyFunction_FastCall (co=<optimized out>, args=<optimized out>, nargs=0, globals=<optimized out>) at Python/ceval.c:4906
#16 0x00007f7da64d605d in fast_function (kwnames=0x0, nargs=<optimized out>, stack=<optimized out>, func=0x7f7da6a18ea0) at Python/ceval.c:4941
#17 call_function (pp_stack=pp_stack
entry=0x7ffc8905b030, oparg=<optimized out>, kwnames=kwnames
entry=0x0) at Python/ceval.c:4845
#18 0x00007f7da64db3f6 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3322
#19 0x00007f7da64d5afa in _PyEval_EvalCodeWithName (_co=0x120, _co
entry=0x7f7da69eeae0, globals=0x3d33728, globals
entry=0x7f7da6a2f0d8, locals=0xfffffffea99ede2f, locals
entry=0x7f7da6a2f0d8, args=0x0, argcount=576, argcount
entry=0, kwnames=0x1b00, kwnames
entry=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at Python/ceval.c:4153
#20 0x00007f7da64d60ce in PyEval_EvalCodeEx (_co=_co
entry=0x7f7da69eeae0, globals=globals
entry=0x7f7da6a2f0d8, locals=locals
entry=0x7f7da6a2f0d8, args=args
entry=0x0, argcount=argcount
entry=0, kws=kws
entry=0x0, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0) at Python/ceval.c:4174
#21 0x00007f7da64d60fb in PyEval_EvalCode (co=co
entry=0x7f7da69eeae0, globals=globals
entry=0x7f7da6a2f0d8, locals=locals
entry=0x7f7da6a2f0d8) at Python/ceval.c:730
#22 0x00007f7da650a4ee in run_mod (arena=0x7f7da6a48318, flags=0x7ffc8905b310, locals=0x7f7da6a2f0d8, globals=0x7f7da6a2f0d8, filename=0x7f7da6933a98, mod=0xce5228) at Python/pythonrun.c:980
#23 PyRun_FileExFlags (fp=<optimized out>, filename_str=<optimized out>, start=<optimized out>, globals=0x7f7da6a2f0d8, locals=0x7f7da6a2f0d8, closeit=1, flags=0x7ffc8905b310) at Python/pythonrun.c:933
#24 0x00007f7da650a666 in PyRun_SimpleFileExFlags (fp=0xcc48a0, filename=0x7f7da697ac90 "test_python_lm_recon.py", closeit=1, flags=0x240, flags
entry=0x7ffc8905b310) at Python/pythonrun.c:396
#25 0x00007f7da650aaf3 in PyRun_AnyFileExFlags (fp=fp
entry=0xcc48a0, filename=<optimized out>, closeit=closeit
entry=1, flags=flags
entry=0x7ffc8905b310) at Python/pythonrun.c:80
#26 0x00007f7da6526e7f in run_file (p_cf=0x7ffc8905b310, filename=0xca2260 L"test_python_lm_recon.py", fp=0xcc48a0) at Modules/main.c:338
#27 Py_Main (argc=argc
entry=2, argv=argv
entry=0xca1010) at Modules/main.c:809
#28 0x0000000000400b61 in main (argc=2, argv=<optimized out>) at ./Programs/python.c:69
===========================================================


The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00007f7d9e8fc8f1 in stir::CListEventCylindricalScannerWithDiscreteDetectors::get_bin(stir::Bin&, stir::ProjDataInfo const&) const () from /home/rmaprrt/bin/STIR_bin/install/python/_stir.so
#7  0x00007f7d9e99cc37 in stir::PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin<stir::DiscretisedDensity<3, float> >::compute_sub_gradient_without_penalty_plus_sensitivity(stir::DiscretisedDensity<3, float>&, stir::DiscretisedDensity<3, float> const&, int) () from /home/rmaprrt/bin/STIR_bin/install/python/_stir.so
#8  0x00007f7d9e8e3ab9 in stir::OSMAPOSLReconstruction<stir::DiscretisedDensity<3, float> >::update_estimate(stir::DiscretisedDensity<3, float>&) () from /home/rmaprrt/bin/STIR_bin/install/python/_stir.so
#9  0x00007f7d9e9371b5 in stir::IterativeReconstruction<stir::DiscretisedDensity<3, float> >::reconstruct(boost::shared_ptr<stir::DiscretisedDensity<3, float> > const&) () from /home/rmaprrt/bin/STIR_bin/install/python/_stir.so
#10 0x00007f7d9e808662 in _wrap_IterativeReconstruction3DFloat_reconstruct () from /home/rmaprrt/bin/STIR_bin/install/python/_stir.so
#11 0x00007f7da643de29 in _PyCFunction_FastCallDict (func_obj=0x7f7d69d507e0, args=0xcfad38, nargs=<optimized out>, kwargs=kwargs
entry=0x0) at Objects/methodobject.c:234
#12 0x00007f7da643e0d7 in _PyCFunction_FastCallKeywords (func=func
entry=0x7f7d69d507e0, stack=stack
entry=0xcfad38, nargs=<optimized out>, kwnames=kwnames
entry=0x0) at Objects/methodobject.c:294
#13 0x00007f7da64d5e83 in call_function (pp_stack=pp_stack
entry=0x7ffc8905ae60, oparg=<optimized out>, kwnames=kwnames
entry=0x0) at Python/ceval.c:4824
#14 0x00007f7da64db3f6 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3322
#15 0x00007f7da64d5150 in _PyFunction_FastCall (co=<optimized out>, args=<optimized out>, nargs=0, globals=<optimized out>) at Python/ceval.c:4906
#16 0x00007f7da64d605d in fast_function (kwnames=0x0, nargs=<optimized out>, stack=<optimized out>, func=0x7f7da6a18ea0) at Python/ceval.c:4941
#17 call_function (pp_stack=pp_stack
entry=0x7ffc8905b030, oparg=<optimized out>, kwnames=kwnames
entry=0x0) at Python/ceval.c:4845
#18 0x00007f7da64db3f6 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3322
#19 0x00007f7da64d5afa in _PyEval_EvalCodeWithName (_co=0x120, _co
entry=0x7f7da69eeae0, globals=0x3d33728, globals
entry=0x7f7da6a2f0d8, locals=0xfffffffea99ede2f, locals
entry=0x7f7da6a2f0d8, args=0x0, argcount=576, argcount
entry=0, kwnames=0x1b00, kwnames
entry=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at Python/ceval.c:4153
#20 0x00007f7da64d60ce in PyEval_EvalCodeEx (_co=_co
entry=0x7f7da69eeae0, globals=globals
entry=0x7f7da6a2f0d8, locals=locals
entry=0x7f7da6a2f0d8, args=args
entry=0x0, argcount=argcount
entry=0, kws=kws
entry=0x0, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0) at Python/ceval.c:4174
#21 0x00007f7da64d60fb in PyEval_EvalCode (co=co
entry=0x7f7da69eeae0, globals=globals
entry=0x7f7da6a2f0d8, locals=locals
entry=0x7f7da6a2f0d8) at Python/ceval.c:730
#22 0x00007f7da650a4ee in run_mod (arena=0x7f7da6a48318, flags=0x7ffc8905b310, locals=0x7f7da6a2f0d8, globals=0x7f7da6a2f0d8, filename=0x7f7da6933a98, mod=0xce5228) at Python/pythonrun.c:980
#23 PyRun_FileExFlags (fp=<optimized out>, filename_str=<optimized out>, start=<optimized out>, globals=0x7f7da6a2f0d8, locals=0x7f7da6a2f0d8, closeit=1, flags=0x7ffc8905b310) at Python/pythonrun.c:933
#24 0x00007f7da650a666 in PyRun_SimpleFileExFlags (fp=0xcc48a0, filename=0x7f7da697ac90 "test_python_lm_recon.py", closeit=1, flags=0x240, flags
entry=0x7ffc8905b310) at Python/pythonrun.c:396
#25 0x00007f7da650aaf3 in PyRun_AnyFileExFlags (fp=fp
entry=0xcc48a0, filename=<optimized out>, closeit=closeit
entry=1, flags=flags
entry=0x7ffc8905b310) at Python/pythonrun.c:80
#26 0x00007f7da6526e7f in run_file (p_cf=0x7ffc8905b310, filename=0xca2260 L"test_python_lm_recon.py", fp=0xcc48a0) at Modules/main.c:338
#27 Py_Main (argc=argc
entry=2, argv=argv
entry=0xca1010) at Modules/main.c:809
#28 0x0000000000400b61 in main (argc=2, argv=<optimized out>) at ./Programs/python.c:69
===========================================================

Segmentation fault
```

### Run sinogram setup then listmode 
If I add another test before the list mode reconstruction which tests sinogram reconstruction (or even just its setup) the list mode reconstruction through python works without fault. Code given here:

```
# run_all.py

print("\n\nTrying to import STIR")
import stir
print("\nSTIR import SUCCESSFUL")

print("\n\nTrying to import STIREXTRA")
import stirextra
print("\nSTIREXTRA import SUCCESSFUL\n\n")

import os
import time

from test_python_sino_recon import *
from test_lm_to_projdata import *
from test_python_lm_recon import *

os.chdir("source")

test_python_sino_recon()

test_python_lm_recon()

```

```
# test_python_sino_recon.py

def test_python_sino_recon():
    import stir
    print("\n\nTESTING SINOGRAM\n")
    parameter_filename = "simple_cylinder.par"

    recon = stir.OSMAPOSLReconstruction3DFloat(parameter_filename)
    current_estimate_target = recon.get_initial_data_ptr()
#    recon.get_objective_function().set_use_subset_sensitivities(False)
    recon.set_up(current_estimate_target)
#    current_estimate_target.fill(1)
#
#    recon.reconstruct(current_estimate_target)
    print("\n\nPASSED SINO RECON\n\n")

if __name__ == "__main__":
    import os, time
    os.chdir("source")
    test_python_sino_recon()
```

### Comments
By running the   
```
recon = stir.OSMAPOSLReconstruction3DFloat(parameter_filename)
current_estimate_target = recon.get_initial_data_ptr()
#recon.get_objective_function().set_use_subset_sensitivities(False)
recon.set_up(current_estimate_target)
```

in a separate function allows for list mode file to be read. Neither of the objects (recon or current_estimate_target) are returned to the parent script. 

I am tempted to say that this is a swig issue but I also wonder if there is something within the sinogram python setup that allows for the correct setup of paths (maybe the shared library /lib64/libc.so.6 ? ) to be properly setup within the python stir module.

**Comment by robbietuk** [comment]
This no longer seems to be an issue. I am closing because it was likely an issue with versions of python.
