### ISSUE TITLE
Travis OSX failure for numpy: _aligned_alloc

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#783]
https://travis-ci.org/github/UCL/STIR/jobs/751991585#L6964 shows the following
```
-- Found PythonInterp: /usr/local/bin/python3 (found version "3.9.1") 
-- Found PythonLibs: /usr/local/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib (found version "3.9.1") 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/usr/local/lib/python3.9/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/usr/local/lib/python3.9/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen(/usr/local/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so, 2): Symbol not found: _aligned_alloc
  Referenced from: /usr/local/opt/gcc/lib/gcc/10/libgomp.1.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/opt/gcc/lib/gcc/10/libgomp.1.dylib
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/usr/local/lib/python3.9/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.
We have compiled some common reasons and troubleshooting tips at:
    https://numpy.org/devdocs/user/troubleshooting-importerror.html
Please note and check the following:
  * The Python version is: Python3.9 from "/usr/local/opt/python@3.9/bin/python3.9"
  * The NumPy version is: "1.19.4"
and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.
Original error was: dlopen(/usr/local/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so, 2): Symbol not found: _aligned_alloc
  Referenced from: /usr/local/opt/gcc/lib/gcc/10/libgomp.1.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/opt/gcc/lib/gcc/10/libgomp.1.dylib
```
This seems to be an OpenMP-related conflict somehow.

**Comment by robbietuk** [comment]
Can close now since we dont use Travis?

**Comment by KrisThielemans** [comment]
ah, another `numpy.core.multiarray` problem! as in #979. Hopefully #985 will prevent these things from coming up again. In any case, this one is indeed obsolete.
