### ISSUE TITLE
STIR python - volume addition issues

### ISSUE THREAD

**Issue by robbietuk** [UCL/STIR#863]
In python, I have:
```
>> type(STIR_image)
<class 'stir.FloatVoxelsOnCartesianGrid'>
```
Trying to add a scalar float results in an error:
```
>> STIR_image += 1.0
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
TypeError: unsupported operand type(s) for +=: 'stir.FloatVoxelsOnCartesianGrid' and 'float'
```
Trying to add itself onto itself results in a error:
```
>> STIR_image += STIR_image
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
TypeError: unsupported operand type(s) for +=: 'stir.FloatVoxelsOnCartesianGrid' and 'stir.FloatVoxelsOnCartesianGrid'
```

This is because the `STIR_image does not have the `__add__` method:
```
help(STIR_image)
Help on FloatVoxelsOnCartesianGrid object:
class FloatVoxelsOnCartesianGrid(Float3DDiscretisedDensityOnCartesianGrid)
 |  stir::VoxelsOnCartesianGrid< float >
 |  
 |  Method resolution order:
 |      FloatVoxelsOnCartesianGrid
 |      Float3DDiscretisedDensityOnCartesianGrid
 |      Float3DDiscretisedDensity
 |      FloatArray3D
 |      builtins.SwigPyObject
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __le__(self, value, /)
 |      Return self<=value.
 |  
 |  __lt__(self, value, /)
 |      Return self<value.
 |  
 |  __ne__(self, value, /)
 |      Return self!=value.
 |  
[cut for clarity]
```

Neither does `stir.FloatArray3D`. However, `stir.FloatNumericVectorWithOffset` does have these methods.
```
help(stir.FloatNumericVectorWithOffset)
Help on class FloatNumericVectorWithOffset in module stir:
class FloatNumericVectorWithOffset(FloatVectorWithOffset)
 |  stir::NumericVectorWithOffset< float,float >
 |  
 |  Method resolution order:
 |      FloatNumericVectorWithOffset
 |      FloatVectorWithOffset
 |      builtins.SwigPyObject
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __iadd__(self, value, /)
 |      Return self+=value.
 |  
 |  __imul__(self, value, /)
 |      Return self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __isub__(self, value, /)
 |      Return self-=value.
 |  
 |  __itruediv__(self, value, /)
 |      Return self/=value.
 |  
 |  __le__(self, value, /)
 |      Return self<=value.
 |  
 |  __lt__(self, value, /)
 |      Return self<value.
 |  
 |  __mul__(self, value, /)
 |      Return self*value.
 |  
 |  __ne__(self, value, /)
 |      Return self!=value.
 |  
 |  __radd__(self, value, /)
 |      Return value+self.
 |  
 |  __rmul__(self, value, /)
 |      Return value*self.
 |  
 |  __rsub__(self, value, /)
 |      Return value-self.
 |  
 |  __rtruediv__(self, value, /)
 |      Return value/self.
 |  
 |  __sub__(self, value, /)
 |      Return self-value.
 |  
 |  __truediv__(self, value, /)
 |      Return self/value.
 |  
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
[...cut for clarity...]
```

Some of these methods were disabled due to matlab as matlab does not have the ability to do: `STIR_image += 1.0` etc.

**Comment by robbietuk** [comment]
`ProjDataInMemory` is a similar case to the above `FloatVoxelsOnCartesianGrid` and `FloatArray3D`

**Comment by robbietuk** [comment]
I have the following work around via `xapyb` to do `z=x+y` with STIR objects.
```
z.xapyb(x, 1, y, 1)
```

**Comment by robbietuk** [comment]
`sapyb()` does not appear to be exposed for `stir::VoxelsOnCartesianGrid`, but `xapyb()` is

**Comment by KrisThielemans** [comment]
sigh. I wonder if this is due to the same SWIG bug (which I still haven't filed, and apparently have never sent to the list (at least, I cannot find it..).

One stupid trick would be to do something like this in the .i file
```
%extend stir::VoxelsOnCartesianGrid {
  void sapyb(float &a,  const Array<3,float>& y, const float b)
   { Array::sapyb(a,y,b); }
}
```
In fact, the same should work for `+=` etc

**Comment by KrisThielemans** [comment]
#1207 added `sapyb`. See comments there on struggles to add the arithmetic operators

**Comment by KrisThielemans** [comment]
I've tried this, see https://github.com/KrisThielemans/STIR-1/blob/8fba04f5ee0869c59941572d29a88c0a2e1f718b/src/swig/stir_array.i#L175-L181

It does "work" as `stir.FloatArray?D` now have `__iadd__` member but using it leads to a corrupted object, and a segfault when it gets deleted.

I've tried to debug the generated code, but cannot spot the problem. I thought to include some of the code anyway.

SWIG  generated an explicit function from the `%extend`
```c++
SWIGINTERN stir::Array< 3,float > &stir_Array_Sl_3_Sc_float_Sg__operator_Sa__Se_(stir::Array< 3,float > *self,stir::Array< 3,float > const &c){
      (*self) += c;
      return *self;
    }
```
and in the `iadd` wrapper we see (aside from type conversion and error checking)
```c++
    result = (stir::Array< 3,float > *) &stir_Array_Sl_3_Sc_float_Sg__operator_Sa__Se_(arg1,(stir::Array< 3,float > const &)*arg2);
    stir::shared_ptr<  stir::Array<3,float> > *smartresult = new stir::shared_ptr<  stir::Array<3,float> >(result SWIG_NO_NULL_DELETER_SWIG_POINTER_OWN);
    resultobj = SWIG_NewPointerObj(SWIG_as_voidptr(smartresult), SWIGTYPE_p_stir__shared_ptrT_stir__ArrayT_3_float_t_t, SWIG_POINTER_OWN);
```
I cannot see what's wrong here (and I've stepped through with gdb and it all seems fine). It is a waste that a new (`shared_ptr` to an) array is created.

As reference, here's what is generated for another type that is not declared with `%shared` (and where everything works fine)
```c++
  result = (stir::BasicCoordinate< 4,float > *) &(arg1)->operator +=((float const &)*arg2);
  resultobj = SWIG_NewPointerObj(SWIG_as_voidptr(result), SWIGTYPE_p_stir__BasicCoordinateT_4_float_t, SWIG_POINTER_OWN |  0 );
```
Note that here, the code does not create a new object, and `resultobj` is created with `flag` 0 (i.e. it is not a new object)

**Comment by KrisThielemans** [comment]
Note that the above behaviour seems exactly what @Robert-PrescientImaging saw as well.

**Comment by KrisThielemans** [comment]
@Robert-PrescientImaging possibly you can already add `operator+` this way. This might not have the same SWIG problem
